ENV['AWS_ACCESS_KEY_ID']='AKIAJ45A74WK4Y7UABNA'
ENV['AWS_SECRET_ACCESS_KEY']='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'
ENV['FOG_DIRECTORY']= 'roomnhouse'
ENV['FOG_PROVIDER']='AWS'
ENV['ASSET_SYNC_GZIP_COMPRESSION']=true
ENV['ASSET_SYNC_MANIFEST']=true