development:
  adapter: postgresql
  encoding: unicode
  database: roomnhouse_development
  pool: 5
  username: fash
  password: amits0lank!

test:
  adapter: postgresql
  encoding: unicode
  database: roomnhouse_test
  pool: 5
  username: fash
  password: amits0lank!


production:
  adapter: postgresql
  encoding: unicode
  pool: 16
  database: d2c12nboi6j4vq
  username: reucmpuucxlubb
  password: 8JpXGqmy9Cmom_hTxX8CHPaP4I
  host: ec2-54-235-243-35.compute-1.amazonaws.com
  port: 5432

