require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FloodsController do

  # This should return the minimal set of attributes required to create a valid
  # Flood. As you add validations to Flood, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "firstname" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FloodsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all floods as @floods" do
      flood = Flood.create! valid_attributes
      get :index, {}, valid_session
      assigns(:floods).should eq([flood])
    end
  end

  describe "GET show" do
    it "assigns the requested flood as @flood" do
      flood = Flood.create! valid_attributes
      get :show, {:id => flood.to_param}, valid_session
      assigns(:flood).should eq(flood)
    end
  end

  describe "GET new" do
    it "assigns a new flood as @flood" do
      get :new, {}, valid_session
      assigns(:flood).should be_a_new(Flood)
    end
  end

  describe "GET edit" do
    it "assigns the requested flood as @flood" do
      flood = Flood.create! valid_attributes
      get :edit, {:id => flood.to_param}, valid_session
      assigns(:flood).should eq(flood)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Flood" do
        expect {
          post :create, {:flood => valid_attributes}, valid_session
        }.to change(Flood, :count).by(1)
      end

      it "assigns a newly created flood as @flood" do
        post :create, {:flood => valid_attributes}, valid_session
        assigns(:flood).should be_a(Flood)
        assigns(:flood).should be_persisted
      end

      it "redirects to the created flood" do
        post :create, {:flood => valid_attributes}, valid_session
        response.should redirect_to(Flood.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved flood as @flood" do
        # Trigger the behavior that occurs when invalid params are submitted
        Flood.any_instance.stub(:save).and_return(false)
        post :create, {:flood => { "firstname" => "invalid value" }}, valid_session
        assigns(:flood).should be_a_new(Flood)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Flood.any_instance.stub(:save).and_return(false)
        post :create, {:flood => { "firstname" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested flood" do
        flood = Flood.create! valid_attributes
        # Assuming there are no other floods in the database, this
        # specifies that the Flood created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Flood.any_instance.should_receive(:update_attributes).with({ "firstname" => "MyString" })
        put :update, {:id => flood.to_param, :flood => { "firstname" => "MyString" }}, valid_session
      end

      it "assigns the requested flood as @flood" do
        flood = Flood.create! valid_attributes
        put :update, {:id => flood.to_param, :flood => valid_attributes}, valid_session
        assigns(:flood).should eq(flood)
      end

      it "redirects to the flood" do
        flood = Flood.create! valid_attributes
        put :update, {:id => flood.to_param, :flood => valid_attributes}, valid_session
        response.should redirect_to(flood)
      end
    end

    describe "with invalid params" do
      it "assigns the flood as @flood" do
        flood = Flood.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Flood.any_instance.stub(:save).and_return(false)
        put :update, {:id => flood.to_param, :flood => { "firstname" => "invalid value" }}, valid_session
        assigns(:flood).should eq(flood)
      end

      it "re-renders the 'edit' template" do
        flood = Flood.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Flood.any_instance.stub(:save).and_return(false)
        put :update, {:id => flood.to_param, :flood => { "firstname" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested flood" do
      flood = Flood.create! valid_attributes
      expect {
        delete :destroy, {:id => flood.to_param}, valid_session
      }.to change(Flood, :count).by(-1)
    end

    it "redirects to the floods list" do
      flood = Flood.create! valid_attributes
      delete :destroy, {:id => flood.to_param}, valid_session
      response.should redirect_to(floods_url)
    end
  end

end
